import { GROUPS } from "./groups";

const {
  BACKGROUND,
  BORDER,
  EFFECTS,
  INTERACTIVITY,
  LAYOUT,
  POSITION,
  SIZE,
  SPACING,
  TYPOGRAPHY,
  SVG
} = GROUPS;

export const classNameGroups: {
  [pattern: string]: string;
} = {
  "-m-": SPACING,
  "-mb-": SPACING,
  "-ml-": SPACING,
  "-mr-": SPACING,
  "-mt-": SPACING,
  "-mx-": SPACING,
  "-my-": SPACING,
  "absolute": POSITION,
  "align-": LAYOUT,
  "antialiased": TYPOGRAPHY,
  "appearance-none": INTERACTIVITY,
  "bg-": BACKGROUND,
  "block": LAYOUT,
  "border": BORDER,
  "bottom-": POSITION,
  "break-": TYPOGRAPHY,
  "capitalize": TYPOGRAPHY,
  "container": SIZE,
  "content-": LAYOUT,
  "cursor-": INTERACTIVITY,
  "fill-current": SVG,
  "m-": SPACING,
  "mb-": SPACING,
  "ml-": SPACING,
  "mr-": SPACING,
  "mt-": SPACING,
  "mx-": SPACING,
  "my-": SPACING,
  "fixed": POSITION,
  "flex": LAYOUT,
  "float": POSITION,
  "font-": TYPOGRAPHY,
  "h-": SIZE,
  "hidden": LAYOUT,
  "inline": LAYOUT,
  "inset-": POSITION,
  "invisible": LAYOUT,
  "italic": TYPOGRAPHY,
  "items-": LAYOUT,
  "justify-": LAYOUT,
  "leading-": TYPOGRAPHY,
  "left-": POSITION,
  "line-through": TYPOGRAPHY,
  "list-": TYPOGRAPHY,
  "lowercase": TYPOGRAPHY,
  "max-": SIZE,
  "min-": SIZE,
  "no-underline": TYPOGRAPHY,
  "normal-case": TYPOGRAPHY,
  "not-italic": TYPOGRAPHY,
  "object-": LAYOUT,
  "opacity-": EFFECTS,
  "order-": LAYOUT,
  "outline-": INTERACTIVITY,
  "overflow-": LAYOUT,
  "p-": SPACING,
  "pb-": SPACING,
  "pl-": SPACING,
  "pointer-events-": INTERACTIVITY,
  "pr-": SPACING,
  "pt-": SPACING,
  "px-": SPACING,
  "py-": SPACING,
  "relative": POSITION,
  "resize": INTERACTIVITY,
  "right-": POSITION,
  "rounded": BORDER,
  "scrolling-": LAYOUT,
  "select-": INTERACTIVITY,
  "self-": LAYOUT,
  "shadow": EFFECTS,
  "stroke-": SVG,
  "subpixel": TYPOGRAPHY,
  "static": POSITION,
  "sticky": POSITION,
  "table": LAYOUT,
  "text-": TYPOGRAPHY,
  "top-": POSITION,
  "tracking-": TYPOGRAPHY,
  "truncate": TYPOGRAPHY,
  "underline": TYPOGRAPHY,
  "uppercase": TYPOGRAPHY,
  "visible": LAYOUT,
  "w-": SIZE,
  "whitespace-": TYPOGRAPHY,
  "z-": POSITION
};
